### ISSUE TITLE
Not able to publish using a windows system. 

### ISSUE THREAD

**Issue by sanjanaadeshra** [opencomponents/oc#1038] opened 2019-05-20 13:15 UTC
I am not able to publish components using a windows system. 

Node version - 10.x.x
oc version - 0.47.0

**Comment by eksted** [comment] 2019-05-23 10:09
I have a same proplem.
If modify cli/facade/publish.js ->  method: putComponentToRegistry and show options.path in log. 
can get "C:\\OC\\my-component\\package.tar.gz", but package.tar.gz not exists

**Comment by eksted** [comment] 2019-05-23 11:25
heroku response: {"error":"package is not valid","details":{"errno":-13,"code":"EACCES","syscall":"mkdir","path":"/app/temp/package-1558610647276/_package/css"}}

**Comment by matteofigus** [comment] 2019-05-30 15:07
Actually closing as this seems to be a duplicate of https://github.com/opencomponents/oc/issues/819

**Closed by matteofigus** 2019-05-30 15:07 UTC
