### ISSUE TITLE
Issue when publishing to registry

### ISSUE THREAD

**Issue by gtrias** [opencomponents/oc#591] opened 2017-08-02 14:52 UTC
Hi, I'm getting this error when trying to publish a component to registry

```

> iltorb@1.3.5 install /builds/alvarium/services/holidays/widgets/node_modules/iltorb
> node-pre-gyp install --fallback-to-build

module.js:471
    throw err;
    ^

Error: Cannot find module 'buffer-shims'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/builds/alvarium/services/holidays/widgets/node_modules/iltorb/node_modules/readable-stream/lib/_stream_readable.js:33:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm info lifecycle iltorb@1.3.5~install: Failed to exec install script
Error: iltorb@1.3.5 install: `node-pre-gyp install --fallback-to-build`
Exit status 1

/usr/local/lib/node_modules/oc/src/cli/domain/load-dependencies.js:41
      throw err;
      ^
Error: iltorb@1.3.5 install: `node-pre-gyp install --fallback-to-build`
Exit status 1
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/oc/node_modules/npm/lib/utils/lifecycle.js:283:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/oc/node_modules/npm/lib/utils/spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
ERROR: Job failed: exit code 1
```
It happens when oc is trying to load dependencies: `Ensuring dependencies are loaded...FAIL`

Registry version: `0.40.1`
oc-client version: `0.40.1`

`.gitlab-ci.yml` related script:

```yaml
deploy:
  stage: deploy
  image: ciricihq/node:lts-oc
  only:
  - tags
  script:
  - yarn --only=production
  - yarn run build
  - oc registry add https://our-registry-url.com
  - NODE_ENV=production oc publish .
```

Any thoughts about this?

**Comment by gtrias** [comment] 2017-08-02 15:04
I'm wondering if it's caused by https://github.com/opentable/oc/commit/d2329cc72964aff97075e4f7ec0d731e2bd3c176

Why is needed to load the dependencies of component when published? Can it be disabled somehow?

**Comment by nickbalestra** [comment] 2017-08-02 15:09
Thanks for reporting this!
Yes, its definitely related to it. (The new template system require the specific template compiler to be present for doing the publishing). 

I'll keep you posted here as soon as we have a solution.

**Comment by gtrias** [comment] 2017-08-02 15:24
Thanks @nickbalestra :)

**Comment by matteofigus** [comment] 2017-08-02 15:36
@gtrias are you able to share your component's `package.json`? I mostly would like to see which deps and dev deps you have. My theory is that you are installing the deps with the flag --production, which means we may be having problems with the devDependencies? Just a theory for now

**Comment by nickbalestra** [comment] 2017-08-02 15:53
That could be @matteofigus, but I'm not sure as If I understood correct yarn uses a different flag (`--production=true` vs `--only`). Though I'm not sure it aliases it to the npm flag.

@gtrias could you try running the CI without the `--only=production` for yarn install to see if that change something?

**Comment by gtrias** [comment] 2017-08-02 15:59
Already tried before without the `--only=production` flag. I've added because in other components I'm deploying with this flag and also was working and I thought the issue was this.

The yarn executed here is to install the modules of the component. Then I build the react javascript using the standard react-create-app build process, then I try to publish with minify set to `false`.
The oc-client is already installed in the image used to deploy using `npm i -g oc`.

**Comment by gtrias** [comment] 2017-08-02 16:02
@matteofigus sorry I didn't see your comment. Here you can see the "obfuscated" package.json:

```json
{
  "name": "new-brand-component",
  "version": "3.1.9",
  "private": true,
  "dependencies": {
    "axios": "^0.16.1",
    "fbjs": "^0.8.12",
    "humps": "^2.0.0",
    "loader": "^2.1.1",
    "moment": "^2.18.1",
    "ms": "^2.0.0",
    "polyfill-service": "^3.18.0",
    "prop-types": "^15.5.10",
    "react": "^15.5.4",
    "react-big-calendar": "^0.14.0",
    "react-bootstrap": "^0.31.0",
    "react-bootstrap-date-picker": "^5.0.1",
    "react-dom": "^15.4.2",
    "react-popover": "^0.4.8",
    "react-redux": "^5.0.3",
    "react-redux-form": "^1.8.1",
    "react-router": "^4.0.0",
    "react-router-dom": "^4.0.0",
    "react-select": "^1.0.0-rc.5",
    "react-signature-canvas": "^0.1.7",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0",
    "underscore": "^1.8.3",
    "webpack-polyfill-service-plugin": "^0.0.4",
    "xlsx-populate": "^1.7.0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.1",
    "babel-core": "^6.24.1",
    "babel-eslint": "^7.1.1",
    "babel-jest": "^20.0.3",
    "babel-loader": "^7.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-app": "^3.0.0",
    "babel-runtime": "^6.20.0",
    "case-sensitive-paths-webpack-plugin": "1.1.4",
    "chalk": "1.1.3",
    "connect-history-api-fallback": "1.3.0",
    "cross-spawn": "^5.1.0",
    "css-loader": "^0.28.0",
    "detect-port": "^1.1.1",
    "dotenv": "^4.0.0",
    "eslint": "^3.16.1",
    "eslint-config-react-app": "^1.0.3",
    "eslint-formatter-pretty": "^1.1.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-flowtype": "2.33.0",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-jsx-a11y": "5.0.1",
    "eslint-plugin-react": "7.0.1",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.11.1",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.28.0",
    "http-proxy-middleware": "^0.17.4",
    "jest": "^20.0.3",
    "json-loader": "0.5.4",
    "node-sass": "^4.5.1",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "^3.0.0",
    "postcss-loader": "^2.0.5",
    "promise": "7.1.1",
    "raw-loader": "^0.5.1",
    "react-dev-utils": "^1.0.3",
    "react-error-overlay": "^1.0.5",
    "sass-loader": "^6.0.3",
    "style-loader": "^0.18.0",
    "sw-precache-webpack-plugin": "^0.9.2",
    "url-loader": "^0.5.8",
    "webpack": "^2.5.1",
    "webpack-dev-server": "^2.4.5",
    "webpack-manifest-plugin": "1.1.0",
    "whatwg-fetch": "^2.0.3"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom",
    "postversion": "git push && git push --tags --no-verify",
    "eslint": "eslint --format=node_modules/eslint-formatter-pretty src"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>[/\\\\](build|docs|node_modules|scripts)[/\\\\]"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    }
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "oc": {
    "minify": false,
    "files": {
      "template": {
        "type": "handlebars",
        "src": "oc/template.html"
      },
      "static": [
        "build/static"
      ],
      "data": "oc/server.js"
    }
  }
}

```

**Comment by nickbalestra** [comment] 2017-08-02 16:07
Publishing from your machine and not CI works?

**Comment by gtrias** [comment] 2017-08-02 16:15
Nope, I've get the exactly same error :(

My local machine versions:
```
genar@kelymaster:~/src/components/holidays-widgets$ node -v
v6.10.0
genar@kelymaster:~/src/components/holidays-widgets$ npm -v
3.10.10
genar@kelymaster:~/src/components/holidays-widgets$ yarn -v
yarn install v0.23.4
```

docker image is extending from node:latest so node version is: v8.2.1

**Comment by nickbalestra** [comment] 2017-08-02 16:22
mmmm thanks a lot for the info. Out of curiosity if you use npm instead of yarn will make it any difference?

**Comment by gtrias** [comment] 2017-08-02 16:38
lol it makes difference...
The publish enters in an infinite loop

```bash
$ rm -rf node_modules/ build/
$ npm i <-- ok
$ npm run build <-- ok
$ NODE_ENV=production oc publish . <-- It enters in an infinite loop, it seems is removing some of the already installed dependencies, maybe the dev ones...
Ensuring dependencies are loaded...FAIL
Trying to install missing modules: fbjs@^0.8.14
If you aren't connected to the internet, or npm isn't configured then this step will fail
+ fbjs@0.8.14
added 1 package, removed 865 packages and updated 117 packages in 15.014s
Ensuring dependencies are loaded...FAIL
Trying to install missing modules: fbjs@^0.8.14
If you aren't connected to the internet, or npm isn't configured then this step will fail
+ fbjs@0.8.14
updated 1 package in 2.205s
Ensuring dependencies are loaded...FAIL
Trying to install missing modules: fbjs@^0.8.14
If you aren't connected to the internet, or npm isn't configured then this step will fail
+ fbjs@0.8.14
updated 1 package in 2.208s
Ensuring dependencies are loaded...FAIL
Trying to install missing modules: fbjs@^0.8.14
If you aren't connected to the internet, or npm isn't configured then this step will fail
+ fbjs@0.8.14
updated 1 package in 2.342s
Ensuring dependencies are loaded...FAIL
Trying to install missing modules: fbjs@^0.8.14
If you aren't connected to the internet, or npm isn't configured then this step will fail
+ fbjs@0.8.14
updated 1 package in 2.792s
Ensuring dependencies are loaded...FAIL
Trying to install missing modules: fbjs@^0.8.14
If you aren't connected to the internet, or npm isn't configured then this step will fail
+ fbjs@0.8.14
updated 1 package in 2.731s
Ensuring dependencies are loaded...FAIL
Trying to install missing modules: fbjs@^0.8.14
If you aren't connected to the internet, or npm isn't configured then this step
```

**Comment by gtrias** [comment] 2017-08-02 16:59
It is happening something weird, When I execute `NODE_ENV=production oc publish .` it is changing my `package.json` contents and creating a `package-lock.json` file...
AFAIK is upgrading my component dependencies... It seems oc-client needs to manage a package.json from where it is executed in order to publish the package.

I thought the issue was running `oc publish .` from the component folder, but executing the command from upper folder doesn't work either.

**Comment by nickbalestra** [comment] 2017-08-02 17:08
Thats npm 5 and should be ok. 
We found the issue is the `fbjs` package as its not requirable as normal packages and we check by requiring. Will work on a fix tomorrow.

**Comment by gtrias** [comment] 2017-08-02 17:19
But upgrading all component dependencies is something dangerous IMHO. I still don't get the point in doing so..

Thanks a lot @nickbalestra. Should be possible to disable the load-dependencies phase of oc publish somehow? Or it's required also for buil-in template engines?

**Comment by matteofigus** [comment] 2017-08-02 19:22
@gtrias I think the best for the time being is to lock OC to 0.39.X to achieve that. 
We have a fix in mind and that should be out tomorrow with a new patch on 0.40.x

**Comment by nickbalestra** [comment] 2017-08-03 10:17
@gtrias #592 should fix it. 

In your scenario, If I understand correctly, you shouldn't need to worry about being able to disable the `load-dependencies` phase as you're already running install before publish, therefore `load-dependencies` should just find them and skip successfully. 

I'll leave this open until we merge and publish the fix, if it solves it, feel free to close this

**Comment by gtrias** [comment] 2017-08-03 10:34
It works now :confetti_ball: . Thank you guys!

**Comment by gtrias** [comment] 2017-08-31 14:00
Hi guys, 
I've found other case in which it breaks the publishing phase (it was working before this issue related upgrade).

I have a compenent which uses a private npm package. Defined in `package.json` in git+ssh format (i.e     `"some-package": "git+ssh://git@git.server.com:namespace/some-package.git"`).

oc-client tries to publish this component it enters in an infinite loop in the step `Ensuring dependencies are loaded...FAIL`... 

Any tip in how can publish this component?

**Comment by nickbalestra** [comment] 2017-08-31 14:16
Sounds like an edge case we don't handle.

Will you like to attempt a PR to add support for this usecase?
A think that a good starting point will be [laod-dependencies.js ](https://github.com/opentable/oc/blob/b62b3405b62ff9f5fabbf8ed34bfab55b49e8b8e/src/cli/domain/load-dependencies.js#L27). 

The npm Installer should be able to support installing from such locations... @matteofigus perhaps this could be the a good occasion to move to cross spawn for this as per #593

**Comment by gtrias** [comment] 2017-08-31 14:43
Thanks @nickbalestra 

I can try to make a PR but I should understand how it is determined what modules are missing at all.
The CI server script executed is the next:
```yaml
deploy:
  stage: deploy
  image: ciricihq/node:lts-oc
  only:
  - tags
  script:
  - yarn --only=production
  - yarn run build
  - oc registry add https://our-registry-url.com
  - NODE_ENV=production oc publish .
```
So the module is already installed under node_modules before build and publish steps are executed...
What do you mean by manually install the specific dep? Make a `yarn add dep`?

**Comment by nickbalestra** [comment] 2017-08-31 14:59
mmm `yarn install` ? (not sure what yarn --only does).
Perhaps trying first to replicate this by trying to publish from local could help debug this, did you try that already? Could you try with npm instead? As we use npm underneath atm there could be an issue when using yearn, we don't have any tests for yarn and we cannot claim support for it atm. The issues I mentioned above could be a first step toward that direction.

**Comment by gtrias** [comment] 2017-08-31 16:09
Tomorrow I'll try what you say because righ now I can build my project using yarn but not using npm... :sweat_smile:

**Comment by gtrias** [comment] 2017-09-01 09:28
I made a refactor to my component to have the right versions for npm as for yarn so now I an test the deploy using npm istead of yarn.

Note that is happening exactly the same (Infinite loop trying to install the missing dependecies). But I have good news! I found a workarround, installing my private dependency as devDependency fix the problem :), not sure if is a very elegant solution but since I'm installing all dependencies when I compile the react component as a webpack "binary" It makes no difference in the workflow...

So in my ci routines I make `npm install` instead of `npm install --production`.

**Comment by elboletaire** [comment] 2017-11-10 13:23
Same issue here, both using npm and yarn.

The workaround from @gtrias works, but it hurts me a bit moving production dependencies to the `devDependencies` and having to install them all 😖

**Comment by matteofigus** [comment] 2017-11-10 13:27
Thanks @elboletaire - as far as I can tell, the whole dependency handler is been completely rewritten - so most of the previous comments shouldn't apply. Have you tried with 0.42.x?

**Comment by elboletaire** [comment] 2017-11-10 15:12
With version 0.42.0 fails with another error:

![imatge](https://user-images.githubusercontent.com/153305/32664524-cb35d7d2-c631-11e7-8d88-7d9a681a7219.png)

Whilst using 0.41.13 (I'm here due to #730) does not have this issue, but enters in a loop, as stated before.

**Comment by elboletaire** [comment] 2017-11-10 15:15
Using version 0.41.16 also throws the `logger.fail('FAIL')` error.

**Comment by matteofigus** [comment] 2017-11-30 17:55
@elboletaire can you retry with latest? (0.42.6)
Thanks

**Comment by elboletaire** [comment] 2018-01-08 15:38
Let me assign this to myself, so I can remember it easily.

**Comment by matteofigus** [comment] 2019-05-30 15:08
I haven't heard of issues anymore and OC publish is working apart from a specific issue with Windows which is tracked in https://github.com/opencomponents/oc/issues/819 - so I am closing this. We can reopen if needed.

**Closed by matteofigus** 2019-05-30 15:08 UTC
Labels: bug, cli
