### ISSUE TITLE
OC publish fails on components with alias dependencies

### ISSUE THREAD

**Issue by ashmeet-kandhari** [opencomponents/oc#1366] opened 2024-05-07 15:43 UTC
## _Who_ is the bug affecting?

- The bug is affecting component creators, while publishing the components having dependency versions as npm aliases

## _What_ is affected by this bug?

- Component publishing

## _When_ does this occur?

- When the component dependencies has npm alias dependencies . For example
```
"dependencies": {
  "case-1.5.3": "npm:case@^1.5.3",
  "kool": "npm:case@^1.6.1"
}
```

## _How_ do we replicate the issue?

- Have a component with npm alias dependency and try to publish

## Expected behavior (i.e. solution)

- Components to be published, irrespective of the type of dependency version.

## What version of OC, Node.js and OS are you using?

- v0.49.43+

**Comment by ricardo-devis-agullo** [comment] 2024-05-07 16:13
Interesting. What's the use case for an alias? Is that a dependency you are using on the client or on the server?

**Comment by ashmeet-kandhari** [comment] 2024-05-07 16:34
We are using in both client and server.
We observed the failure only while publishing the components (it doesn't publish)

**Comment by ricardo-devis-agullo** [comment] 2024-05-07 16:46
what's the use case of needing this, though?

**Comment by ashmeet-kandhari** [comment] 2024-05-07 16:54
Ah sorry,
On the server side we have components using different versions of same
dependency.

And we cannot change the versions as different components are using
different versions

**Comment by ricardo-devis-agullo** [comment] 2024-05-07 17:31
Can you post exactly the error you get when publishing?

**Comment by ashmeet-kandhari** [comment] 2024-05-07 19:09
Here is the error 
```
oc package --useComponentDependencies /drone/src/github/test-component

exec_node: ====================================================
exec_node: INFO: Performing Node Run-Time and V8 Engine configuration
exec_node: INFO: Making Run-Time and Engine options ( 'max-http-header-size=131072' ) console safe...
'package' '--useComponentDependencies' '/drone/src/github/test-component'
exec_node: ====================================================

Packaging -> /drone/src/github/test-component/_package
Ensuring dependencies are loaded...
Trying to link missing modules: @internal/dependent-components-2@npm:@nternal/dependent-components@2.1.0, react-dom17@npm:react-dom@17.0.2, react17@npm:react@17.0.2

The missing dependencies will be linked to component dependenciesAn error happened when linking the dependency @internal/dependent-components-2@npm:@internal/dependent-components with error Error: ENOENT: no such file or directory, ensureSymlink '/drone/src/github/test-component/node_modules/@internal/dependent-components-2@npm:@internal/dependent-components'
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
```

**Comment by ricardo-devis-agullo** [comment] 2024-05-07 20:45
oc package works for me when having this

"case-1.5.3": "npm:case@^1.5.3"

can you give me a repository where I can reproduce?

**Comment by ashmeet-kandhari** [comment] 2024-05-08 10:53
Hi @ricardo-devis-agullo , 
I think this was an issue on our side (this was done long time ago so forgot) where the way our CI pipeline is setup we were not able to download the missing dependencies  in this step `Ensuring dependencies are loaded...` 

And when the issue was investigated we found that the component alias dependencies were not resolving due to the alias issue in the pr that I have raised.

Hope that answers your question

**Comment by ricardo-devis-agullo** [comment] 2024-05-08 19:04
Yeah, that makes sense! I will close the issue then :)

**Closed by ricardo-devis-agullo** 2024-05-08 19:04 UTC
